spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/onlineShop
    password: root
    username: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: false
    database: postgresql
server:
  port: 2222